# Introduction to Numpy

In this noteboook we will focus on the following areas:
- Creating arrays
- Multidimensional arrays
- Randomly generated arrays
- Elementwise operations
    - Comparison operations
    - Logical operations
- Summarising operations

In [3]:
# Imports
import numpy as np

## Creating Arrays

In [4]:
# Array of zeros (5)
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
# Array of ones (10)
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# Create an array with ten elements all with a value of 3.5
np.full(10, 3.5)

array([3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5])

In [7]:
# We can also convert a list into an array using np.array
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [8]:
# Elements of the array can be accessed via index just like a list
a[2]

np.int64(3)

In [9]:
# We can also create an array as a range from zero to a number or between two numbers
np.arange(19)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [11]:
# Create array between two values with equal space between each value
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Multi-dimensional Arrays

In [12]:
# Two dimensional array (matrix)
np.zeros((5, 3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Randomly generated arrays

In [14]:
np.random.rand(5, 2)

array([[0.4906997 , 0.93347454],
       [0.09416542, 0.82169221],
       [0.12470836, 0.95932816],
       [0.15263514, 0.39512629],
       [0.45543599, 0.46863266]])

In [16]:
# We can set the seed to get the same random values, making it reproducible
np.random.seed(42)
np.random.rand(5, 2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

In [17]:
# create rand within normal distribution
np.random.randn(5, 2)

array([[-0.46947439,  0.54256004],
       [-0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024],
       [-1.72491783, -0.56228753],
       [-1.01283112,  0.31424733]])

In [18]:
# Setting random within a range
np.random.randint(low=0, high=100, size=(5,3))

array([[91, 59, 79],
       [14, 61, 61],
       [46, 61, 50],
       [54, 63,  2],
       [50,  6, 20]])

## Elementwise Operations

In [22]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [21]:
# Add to each element of the array
a + 2

array([2, 3, 4, 5, 6])

In [24]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [25]:
# Adding to arrays adds the two elements of same index together
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison operations

In [26]:
a

array([0, 1, 2, 3, 4])

In [27]:
a >= 2

array([False, False,  True,  True,  True])

In [28]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [29]:
a > b

array([False, False,  True,  True,  True])

## Summarising operations
Think summary statistics

In [30]:
a 


array([0, 1, 2, 3, 4])

In [31]:
a.min()


np.int64(0)

In [32]:
a.sum()

np.int64(10)