# 1.8 Linear algebra Refresher

## Vector operations

In [1]:
import numpy as np

In [2]:
u = np.array([2, 5, 7, 1])
v = np.array([3, 4, 8, 6])

In [3]:
# Adding two vectors
u + v

array([ 5,  9, 15,  7])

In [4]:
# scalar multiplication (not the same as dot product)
u * v

array([ 6, 20, 56,  6])

## Vector vector multiplication

In this instance we are looking for the dot product of two vectors.

In [5]:
def vec_vec_dot_prod(u: np.array,v: np.array) -> float:
    """Function to find the dot product of two vectors."""
    assert u.shape[0] == v.shape[0] # check dimensions of vectors are the same.

    result = 0.0

    for i in range(u.shape[0]):
        result += (u[i] * v[i])

    return result


In [7]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [8]:
print(vec_vec_dot_prod(u, v))

14.0


## Matrix vector multiplication

In [12]:
def mat_vec_dot_prod(U: np.array,v: np.array)-> np.array:
    """Function to find the dot product of a matrix and a vector."""
    assert U.shape[1] == v.shape[0] # check dimensions of matrix row vector and vector are the same.
    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vec_vec_dot_prod(U[i], v)

    return result

In [15]:
U = np.array([[2, 4, 6, 8],
              [1, 2, 3, 4],
              [5, 6, 7, 8],])

v = np.array([1, 0.5, 2, 1])

In [16]:
mat_vec_dot_prod(U, v)

array([24., 12., 30.])

## Matrix matrix multiplication

In [17]:
def mat_dot_prod(U: np.array,V: np.array)-> np.array:
    """Function to find the dot product of 2 matrices."""
    assert U.shape[1] == V.shape[0] # check dimensions of matrix row vector and vector are the same.
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        result_col = mat_vec_dot_prod(U, V[:, i])
        result[:, i] = result_col

    return result

In [18]:
U = np.array([[2, 4, 5, 6],
              [2, 1, 2, 1],
              [3, 1, 2, 1],])

V = np.array([[1, 1, 2],
              [0, 0.5, 1],
              [0, 2, 1],
              [1, 1, 0]])

In [19]:
mat_dot_prod(U, V)

array([[ 8. , 20. , 13. ],
       [ 3. ,  7.5,  7. ],
       [ 4. ,  8.5,  9. ]])

## Identity Matrix

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Inverse of a square matrix

In [21]:
V = np.array([[1, 1, 2],
              [0, 0.5, 1],
              [0, 2, 1]])

inv_v = np.linalg.inv(V)

In [22]:
inv_v

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [23]:
mat_dot_prod(V, inv_v)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])